name = "julia-intro"
uuid = "c0ea12e0-a9e8-11e8-3aaa-d59a3207d622"
authors = ["Tim Besard <tim.besard@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
